# Generated by Django 5.0.2 on 2024-03-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Amount', models.PositiveIntegerField()),
            ],
        ),
    ]
